# I wouldn't normally commit a config file but since it's just for learns
application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@tmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 5000
